### PR TITLE
refact(plugins): each plugin in a separate pkg

### PR DESCRIPTION
**Pull request by rafaelrubbioli**
For better readability and usage, each plugin is now in a subpackage of the plugin pkg.

closes https://github.com/tfaughnan/artoo/issues/4

### CODE REVIEW

**Comment by tfaughnan** [comment]
This looks good. Can you also rename the pattern and handler for each of
the two plugins to just be `Pattern` and `Handler`?

E.g.`echo.EchoPattern` and `echo.EchoHandler` -> `echo.Pattern` and
`echo.Handler`

**Comment by rafaelrubbioli** [comment]
@tfaughnan sure! do you also think is a good idea to rename internal names such as `openaiRespPayload` to `respPayload`?

**Comment by tfaughnan** [comment]
Yes those should be renamed to remove the redundant prefix -- good catch.

**Comment by rafaelrubbioli** [comment]
@tfaughnan done!

**Comment by tfaughnan** [comment]
LGTM, thanks!

**Pull request merged**
